const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const PORT=Number(process.env.PORT||10000);const DATA=process.env.ACCOUNTS_FILE||path.join(__dirname,'accounts.json');
let accounts=loadAccounts();const sessions=new Map();
let mapState={updatedAt:0,mapPoints:[],mapHidden:[],fleet:[],members:[],qrus:[]};let permissionsState={};const clients=new Set();
function loadAccounts(){try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch{return []}}
function saveAccounts(){const dir=path.dirname(DATA);if(dir&&dir!=='.')fs.mkdirSync(dir,{recursive:true});const tmp=DATA+'.tmp';fs.writeFileSync(tmp,JSON.stringify(accounts,null,2));fs.renameSync(tmp,DATA)}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return new Promise((resolve,reject)=>crypto.scrypt(password,salt,64,(e,k)=>e?reject(e):resolve({salt,hash:k.toString('hex')})))}
async function verifyPassword(password,a){const h=await hashPassword(password,a.salt);return crypto.timingSafeEqual(Buffer.from(h.hash,'hex'),Buffer.from(a.hash,'hex'))}
function cleanUsername(v){return String(v||'').trim().toLowerCase()}
function token(){return crypto.randomBytes(32).toString('hex')}
function json(res,status,data,extra={}){const body=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS',...extra});res.end(body)}
function collect(req,cb){let raw='';req.on('data',c=>{raw+=c;if(raw.length>2e6)req.destroy()});req.on('end',()=>cb(raw))}
function cookieToken(req){const m=String(req.headers.cookie||'').match(/(?:^|;\s*)prf_session=([^;]+)/);return m?m[1]:null}
function currentUser(req){const t=cookieToken(req);const u=t&&sessions.get(t);if(!u)return null;return accounts.find(a=>a.id===u)||null}
function publicUser(a){return a&&{id:a.id,name:a.name,memberId:a.memberId,username:a.username,role:a.role}}
function requireUser(req,res){const u=currentUser(req);if(!u){json(res,401,{ok:false,error:'Faça login para continuar.'});return null}return u}
function safeSnapshot(input){const clean=(arr,keys)=>Array.isArray(arr)?arr.slice(0,500).map(x=>{const o={};for(const k of keys)if(x&&x[k]!==undefined)o[k]=x[k];return o}):[];return{updatedAt:Date.now(),mapPoints:clean(input.mapPoints,['id','name','kind','mapX','mapY','status','owner','leader','team','date']),mapHidden:Array.isArray(input.mapHidden)?input.mapHidden.slice(0,1000).map(String):[],fleet:clean(input.fleet,['id','prefix','model','status','team','mapX','mapY']),members:clean(input.members,['id','name','rank','status','mapX','mapY']),qrus:clean(input.qrus,['id','number','type','desc','severity','status','mapX','mapY'])}}
function broadcast(){const payload=`data: ${JSON.stringify(mapState)}\n\n`;for(const r of clients){try{r.write(payload)}catch{clients.delete(r)}}}
const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='OPTIONS')return json(res,204,{});
if(url.pathname==='/api/auth/me'&&req.method==='GET'){const u=currentUser(req);return json(res,200,{user:publicUser(u)})}
if(url.pathname==='/api/auth/register'&&req.method==='POST')return collect(req,async raw=>{try{const d=JSON.parse(raw||'{}');const name=String(d.name||'').trim(),memberId=String(d.memberId||'').trim(),username=cleanUsername(d.username),password=String(d.password||'');if(name.length<2||memberId.length<1||username.length<3||password.length<8)return json(res,400,{error:'Preencha nome, ID, usuário e senha (mínimo 8 caracteres).'});if(accounts.some(a=>String(a.username||'').toLowerCase()===username))return json(res,409,{error:'Esse usuário já está cadastrado.'});if(accounts.some(a=>String(a.memberId||'').toLowerCase()===memberId.toLowerCase()))return json(res,409,{error:'Esse ID de membro já está cadastrado.'});const hp=await hashPassword(password);const a={id:'USR-'+crypto.randomBytes(8).toString('hex'),name,memberId,username,salt:hp.salt,hash:hp.hash,role:'Recruta',createdAt:new Date().toISOString()};accounts.push(a);try{saveAccounts()}catch(e){accounts.pop();console.error('Falha ao salvar accounts.json:',e);return json(res,500,{error:'O servidor não conseguiu salvar o cadastro.',detail:String(e.message||e)})}const t=token();sessions.set(t,a.id);const secure=req.headers['x-forwarded-proto']==='https'||req.headers.host?.includes('railway.app');res.setHeader('Set-Cookie',`prf_session=${t}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${secure?'; Secure':''}`);json(res,201,{ok:true,user:publicUser(a)})}catch(e){console.error('Erro no cadastro:',e);json(res,500,{error:'Falha interna no cadastro.',detail:String(e.message||e)})}});
if(url.pathname==='/api/auth/login'&&req.method==='POST')return collect(req,async raw=>{try{const d=JSON.parse(raw||'{}');const a=accounts.find(x=>x.username===cleanUsername(d.username));if(!a||!(await verifyPassword(String(d.password||''),a)))return json(res,401,{error:'Usuário ou senha inválidos.'});const t=token();sessions.set(t,a.id);res.setHeader('Set-Cookie',`prf_session=${t}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800`);json(res,200,{ok:true,user:publicUser(a)})}catch{json(res,401,{error:'Usuário ou senha inválidos.'})}});
if(url.pathname==='/api/auth/logout'&&req.method==='POST'){const t=cookieToken(req);if(t)sessions.delete(t);res.setHeader('Set-Cookie','prf_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0');return json(res,200,{ok:true})}
if(url.pathname==='/api/permissions'&&req.method==='GET'){if(!requireUser(req,res))return;return json(res,200,{permissions:permissionsState})}
if(url.pathname==='/api/permissions'&&req.method==='PUT'){const u=requireUser(req,res);if(!u)return;if(u.role!=='Comando')return json(res,403,{error:'Somente o Comando pode alterar permissões.'});return collect(req,raw=>{try{const d=JSON.parse(raw||'{}');permissionsState=d.permissions&&typeof d.permissions==='object'?d.permissions:{};json(res,200,{ok:true})}catch{json(res,400,{error:'Permissões inválidas.'})}})}
if(url.pathname==='/api/map/state'&&req.method==='GET'){if(!requireUser(req,res))return;return json(res,200,mapState)}
if(url.pathname==='/api/map/state'&&req.method==='PUT'){const u=requireUser(req,res);if(!u)return;if(u.role!=='Comando')return json(res,403,{error:'Somente o Comando pode publicar alterações no mapa.'});return collect(req,raw=>{try{mapState=safeSnapshot(JSON.parse(raw||'{}'));broadcast();json(res,200,{ok:true,updatedAt:mapState.updatedAt})}catch{json(res,400,{error:'Estado do mapa inválido.'})}})}
if(url.pathname==='/api/map/stream'&&req.method==='GET'){if(!requireUser(req,res))return;res.writeHead(200,{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache, no-store, must-revalidate','Connection':'keep-alive','Access-Control-Allow-Origin':'*','X-Accel-Buffering':'no'});res.write(': conectado\n\n');if(mapState.updatedAt)res.write(`data: ${JSON.stringify(mapState)}\n\n`);clients.add(res);req.on('close',()=>clients.delete(res));return}
if(url.pathname==='/health')return json(res,200,{ok:true,service:'PRF Central V13',mapClients:clients.size,accounts:accounts.length});
let fp=url.pathname==='/'?'/index.html':url.pathname;fp=path.normalize(path.join(__dirname,fp));if(!fp.startsWith(__dirname))return json(res,403,{error:'Forbidden'});fs.stat(fp,(e,st)=>{if(e||!st.isFile())return json(res,404,{error:'Não encontrado'});const ext=path.extname(fp).toLowerCase();const types={'.html':'text/html; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(fp).pipe(res)})});
server.listen(PORT,'0.0.0.0',()=>console.log(`PRF Central V13 online na porta ${PORT}`));setInterval(()=>{for(const r of clients){try{r.write(': ping\n\n')}catch{clients.delete(r)}}},20000);
